title: "MIT RRG"
tagline: "MIT ESI Rapid Response Group"
description: "The ESI Rapid Response Group (RRG) was formed to respond to critical environmental issues in a timely manner with science based analysis and assistance in the service of our partners in communities, civil society, government and industry. The RRG generates a variety of targeted materials including synopses of state of the art, briefing documents, fact sheets, talking points, executive summaries, and other products in various media and across a range of important environmental issues. The RRG also serves as a bridge between the MIT community and our partners by connecting individuals and expertise through informal conversations, curated panels, symposia and other knowledge and perspective sharing events."
author: Tareq El Dandachi
github_username: tareqdandachi
baseurl: "/mit-rrg"
url: "https://esiresponse.mit.edu"

lang: en_US

markdown:    kramdown
highlighter: pygments

sass:
  style: compressed

collections:
  projects:
    output: true
    permalink: /projects/:path/
  members:
    output: true
    permalink: /members/:path/

header_pages:
 - index.html
 - about.html
 - projects.html
 - partners.html
