name: Sync Fork

on:
  schedule:
  - cron:  "* * * * *"
  push:
    branches:
      - master

jobs:

  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "tareqdandachi/mit-rrg"
        source_branch: "master"
        destination_branch: "live"
        github_token: ${{ secrets.GITHUB_TOKEN }}

  scripts-sync:
    runs-on: ubuntu-latest
    needs: [repo-sync]
    steps:
    - name: wget
      uses: wei/wget@v1
      with:
        args: http://esiresponse.scripts.mit.edu/scripts_sync/update.php -q -O -
